use crate::CoreError;
use base64::Engine;
use gemini_rust::{Blob, Content, FunctionResponse, GenerationResponse, Part};
use ollama_rs::generation::chat::{ChatMessage, ChatMessageResponse, MessageRole};
use openai_api_rs::v1::chat_completion::{
    ChatCompletionMessage, ChatCompletionMessageForResponse,
    chat_completion_stream::ChatCompletionStreamResponse,
};
use serde::{Deserialize, Serialize};
use std::fmt::Display;

use crate::llm::{FunctionResult, function::FunctionCall};

/// Role of the message author
///
/// Possible values:
/// - System: Instructions or context for the LLM
/// - Tool: Messages generated by tools/functions
/// - Assistant: Responses from the LLM
/// - User: Input from the end-user
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Eq, Hash, PartialOrd, Ord)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    Tool,
    Assistant,
    User,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Image {
    pub url: String,
    pub text: Option<String>,
}

impl Image {
    pub fn new(url: String, text: Option<String>) -> Self {
        Self { url, text }
    }

    #[cfg(feature = "openai")]
    pub fn from_openai(image: openai_api_rs::v1::chat_completion::ImageUrl) -> Self {
        let url = match image.image_url {
            Some(u) => u.url,
            None => "".to_string(),
        };

        Self {
            url,
            text: image.text,
        }
    }

    #[cfg(feature = "openai")]
    pub fn to_openai(&self) -> openai_api_rs::v1::chat_completion::ImageUrl {
        openai_api_rs::v1::chat_completion::ImageUrl {
            r#type: openai_api_rs::v1::chat_completion::ContentType::image_url,
            image_url: Some(openai_api_rs::v1::chat_completion::ImageUrlType {
                url: self.url.clone(),
            }),
            text: self.text.clone(),
        }
    }

    #[cfg(feature = "ollama")]
    pub fn from_ollama(image: ollama_rs::generation::images::Image) -> Self {
        Self {
            url: image.to_base64().to_string(),
            text: None,
        }
    }

    #[cfg(feature = "ollama")]
    pub fn to_ollama(&self) -> ollama_rs::generation::images::Image {
        ollama_rs::generation::images::Image::from_base64(&self.url)
    }

    #[cfg(feature = "google")]
    pub fn from_gemini(image: gemini_rust::Part) -> crate::Result<Self> {
        if let gemini_rust::Part::InlineData { inline_data } = image {
            match inline_data.mime_type.as_str() {
                "image/png" | "image/jpeg" | "image/jpg" | "image/gif" => Ok(Self {
                    url: format!("data:{};base64,{}", inline_data.mime_type, inline_data.data),
                    text: None,
                }),
                _ => Err(Box::from(CoreError::Generic(
                    "Unsupported image MIME type".to_string(),
                ))),
            }
        } else {
            Err(Box::from(CoreError::Generic(
                "Provided part is not an InlineData part".to_string(),
            )))
        }
    }

    #[cfg(feature = "google")]
    pub fn to_gemini(&self) -> gemini_rust::Part {
        let base64_data = if self.url.starts_with("data:") {
            // Extract base64 part from data URL
            self.url
                .split_once(",")
                .map(|x| x.1)
                .unwrap_or("")
                .to_string()
        } else {
            self.url.clone()
        };
        gemini_rust::Part::InlineData {
            inline_data: Blob::new("image/png", base64_data),
        }
    }
}

/// A `Message` in the conversation, which may include text, audio, images, and function calls/results.
/// This is a unified representation that can be converted to/from various LLM formats.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: Role,
    pub message: Option<String>,
    pub audio: Option<Vec<u8>>,

    // Base64 images
    pub images: Option<Vec<Image>>,
    pub thinking: Option<String>,
    pub function_calls: Vec<FunctionCall>,
    pub function_results: Vec<FunctionResult>,
}

impl Display for Message {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Role: {:?}\nMessage: {:?}\nAudio: {}\nImages: {}\nThinking: {:?}\nFunction Calls: {}\nFunction Results: {}",
            self.role,
            self.message,
            if self.audio.is_some() {
                "<audio data>"
            } else {
                "None"
            },
            if let Some(images) = &self.images {
                format!("{} image(s)", images.len())
            } else {
                "None".to_string()
            },
            self.thinking,
            self.function_calls.len(),
            self.function_results.len()
        )
    }
}

impl Message {
    pub fn new(role: Role, message: Option<String>) -> Self {
        Self {
            role,
            message,
            audio: None,
            images: None,
            thinking: None,
            function_calls: vec![],
            function_results: vec![],
        }
    }

    pub fn user(message: impl ToString) -> Self {
        Self::new(Role::User, Some(message.to_string()))
    }

    pub fn assistant(message: impl ToString) -> Self {
        Self::new(Role::Assistant, Some(message.to_string()))
    }

    pub fn system(message: impl ToString) -> Self {
        Self::new(Role::System, Some(message.to_string()))
    }

    pub fn tool(message: impl ToString) -> Self {
        Self::new(Role::Tool, Some(message.to_string()))
    }

    pub fn function_results(results: Vec<FunctionResult>) -> Self {
        Self {
            role: Role::Tool,
            message: None,
            audio: None,
            images: None,
            thinking: None,
            function_calls: vec![],
            function_results: results,
        }
    }

    pub fn add_function_result(mut self, result: FunctionResult) -> Self {
        self.function_results.push(result);
        self
    }

    pub fn add_function_call(mut self, call: FunctionCall) -> Self {
        self.function_calls.push(call);
        self
    }

    pub fn with_audio(mut self, audio: Vec<u8>) -> Self {
        self.audio = Some(audio);
        self
    }

    pub fn with_images(mut self, images: Vec<Image>) -> Self {
        self.images = Some(images);
        self
    }

    pub fn add_image(mut self, image: Image) -> Self {
        if let Some(imgs) = &mut self.images {
            imgs.push(image);
        } else {
            self.images = Some(vec![image]);
        }
        self
    }

    pub fn with_thinking(mut self, thinking: String) -> Self {
        self.thinking = Some(thinking);
        self
    }

    pub fn is_thinking(&self) -> bool {
        self.thinking.is_some()
    }

    pub fn has_function_calls(&self) -> bool {
        !self.function_calls.is_empty()
    }

    pub fn has_function_results(&self) -> bool {
        !self.function_results.is_empty()
    }

    /// Converts this `Message` to a Gemini-compatible message.
    #[cfg(feature = "google")]
    pub fn to_gemini(&self) -> gemini_rust::Message {
        let role = match self.role {
            Role::User => gemini_rust::Role::User,
            _ => gemini_rust::Role::Model,
        };

        let mut content: Content = Content {
            role: Some(role.clone()),
            parts: vec![].into(),
        };

        if let Some(audio) = &self.audio
            && let Some(parts) = &mut content.parts
        {
            let base64 = base64::engine::general_purpose::STANDARD.encode(audio);
            parts.push(Part::InlineData {
                inline_data: Blob::new("audio/mp3", base64),
            });
        }

        if let Some(msg) = &self.message
            && let Some(parts) = &mut content.parts
        {
            parts.push(Part::Text {
                text: msg.clone(),
                thought: Some(self.thinking.is_some()),
                thought_signature: None,
            });
        }

        if !self.function_calls.is_empty()
            && let Some(parts) = &mut content.parts
        {
            for fc in &self.function_calls {
                parts.push(Part::FunctionCall {
                    function_call: fc.to_gemini(),
                    thought_signature: None,
                });
            }
        }

        if !self.function_results.is_empty()
            && let Some(parts) = &mut content.parts
        {
            for fr in &self.function_results {
                parts.push(Part::FunctionResponse {
                    function_response: FunctionResponse {
                        name: fr.name.clone(),
                        response: Some(fr.results.clone()),
                    },
                });
            }
        }

        gemini_rust::Message { role, content }
    }

    /// Converts this `Message` to an Ollama-compatible message.
    #[cfg(feature = "ollama")]
    pub fn to_ollama(&self) -> ChatMessage {
        let images = match &self.images {
            Some(imgs) => imgs.iter().map(|img| img.to_ollama()).collect(),
            None => vec![],
        };

        ChatMessage {
            role: match self.role {
                Role::User => MessageRole::User,
                Role::System => MessageRole::System,
                Role::Tool => MessageRole::Tool,
                Role::Assistant => MessageRole::Assistant,
            },
            content: self.message.clone().unwrap_or_default(),
            tool_calls: self
                .function_calls
                .iter()
                .map(|fc| fc.to_ollama())
                .collect(),
            images: if images.is_empty() {
                None
            } else {
                Some(images)
            },
            thinking: self.thinking.clone(),
        }
    }

    /// Converts this `Message` to an OpenAI-compatible message.
    #[cfg(feature = "openai")]
    pub fn to_openai(&self) -> openai_api_rs::v1::chat_completion::ChatCompletionMessage {
        use openai_api_rs::v1::chat_completion::{
            Content, MessageRole, ToolCall, ToolCallFunction,
        };

        let role = match self.role {
            Role::User => MessageRole::user,
            Role::Assistant => MessageRole::assistant,
            Role::System => MessageRole::system,
            Role::Tool => MessageRole::tool,
        };

        // Convert function_calls to OpenAI tool_calls
        let tool_calls = if self.function_calls.is_empty() {
            None
        } else {
            Some(
                self.function_calls
                    .iter()
                    .enumerate()
                    .map(|(i, fc)| ToolCall {
                        id: format!("call_{}", i),
                        r#type: "function".to_string(),
                        function: ToolCallFunction {
                            name: Some(fc.name.clone()),
                            arguments: Some(fc.arguments.to_string()),
                        },
                    })
                    .collect(),
            )
        };

        // For tool role (function results), we need tool_call_id
        let tool_call_id = if self.role == Role::Tool && !self.function_results.is_empty() {
            // Use the function name as identifier (OpenAI expects the call ID)
            self.function_results.first().map(|fr| fr.name.clone())
        } else {
            None
        };

        // For tool results, content is the result JSON
        let content = if self.role == Role::Tool && !self.function_results.is_empty() {
            Content::Text(
                self.function_results
                    .first()
                    .map(|fr| fr.results.to_string())
                    .unwrap_or_default(),
            )
        } else {
            Content::Text(self.message.clone().unwrap_or_default())
        };

        openai_api_rs::v1::chat_completion::ChatCompletionMessage {
            role,
            content,
            name: None,
            tool_call_id,
            tool_calls,
        }
    }

    /// Converts a Gemini `GenerationResponse` to this `Message` format.
    #[cfg(feature = "google")]
    pub fn from_gemini(gemini_message: GenerationResponse) -> Message {
        let candidate = match gemini_message.candidates.first() {
            Some(c) => c,
            None => {
                return Message {
                    role: Role::Assistant,
                    message: None,
                    audio: None,
                    images: None,
                    thinking: None,
                    function_calls: vec![],
                    function_results: vec![],
                };
            }
        };

        let mut function_calls = vec![];
        let mut message_parts = vec![];
        let mut audio_parts = vec![];
        if let Some(parts) = &candidate.content.parts {
            for part in parts {
                if let Part::FunctionCall { function_call, .. } = part {
                    function_calls.push(FunctionCall::from_gemini(function_call.clone()));
                }

                if let Part::Text { text, .. } = part {
                    message_parts.push(text.clone());
                }

                if let Part::InlineData { inline_data } = part
                    && inline_data.mime_type.starts_with("audio/")
                {
                    let decoded = base64::engine::general_purpose::STANDARD
                        .decode(&inline_data.data)
                        .ok();
                    if let Some(audio_data) = decoded {
                        audio_parts.push(audio_data);
                    }
                }
            }
        }

        Message {
            role: Role::Assistant,
            message: if message_parts.is_empty() {
                None
            } else {
                Some(message_parts.join("\n"))
            },
            audio: if audio_parts.is_empty() {
                None
            } else {
                Some(audio_parts.concat())
            },
            images: None,
            thinking: None,
            function_calls,
            function_results: vec![],
        }
    }

    /// Converts an Ollama `ChatMessageResponse` to this `Message` format.
    #[cfg(feature = "ollama")]
    pub fn from_ollama(ollama_message: ChatMessageResponse) -> Message {
        let images = ollama_message.message.images.as_ref().map(|imgs| {
            imgs.iter()
                .map(|img| Image::from_ollama(img.clone()))
                .collect()
        });

        Message {
            role: match ollama_message.message.role {
                MessageRole::User => Role::User,
                MessageRole::System => Role::System,
                MessageRole::Tool => Role::Tool,
                MessageRole::Assistant => Role::Assistant,
            },
            message: Some(ollama_message.message.content),
            audio: None,
            images,
            thinking: ollama_message.message.thinking,
            function_calls: ollama_message
                .message
                .tool_calls
                .into_iter()
                .map(FunctionCall::from_ollama)
                .collect(),
            function_results: vec![],
        }
    }

    /// Converts an OpenAI `ChatCompletionMessage` to this `Message` format.
    #[cfg(feature = "openai")]
    pub fn from_openai(message: ChatCompletionMessage) -> Message {
        let function_calls = message
            .tool_calls
            .as_ref()
            .map(|tcs| {
                tcs.iter()
                    .map(|tc| FunctionCall::from_openai(tc.clone()))
                    .collect()
            })
            .unwrap_or_default();

        let images = match &message.content {
            openai_api_rs::v1::chat_completion::Content::ImageUrl(image_vec) => Some(
                image_vec
                    .iter()
                    .map(|img| Image::from_openai(img.clone()))
                    .collect(),
            ),
            _ => None,
        };

        Message {
            role: match message.role {
                openai_api_rs::v1::chat_completion::MessageRole::user => Role::User,
                openai_api_rs::v1::chat_completion::MessageRole::system => Role::System,
                openai_api_rs::v1::chat_completion::MessageRole::tool => Role::Tool,
                openai_api_rs::v1::chat_completion::MessageRole::assistant => Role::Assistant,
                _ => Role::Assistant,
            },
            message: Some(match message.content {
                openai_api_rs::v1::chat_completion::Content::Text(text) => text,
                _ => "".to_string(),
            }),
            audio: None,
            images,
            thinking: None,
            function_calls,
            function_results: vec![],
        }
    }

    #[cfg(feature = "openai")]
    pub fn from_openai_chat_completion_message_for_response(
        message: &ChatCompletionMessageForResponse,
    ) -> crate::Result<Message> {
        let function_calls = message
            .tool_calls
            .as_ref()
            .map(|tcs| {
                tcs.iter()
                    .map(|tc| FunctionCall::from_openai(tc.clone()))
                    .collect()
            })
            .unwrap_or_default();

        Ok(Message {
            role: match message.role {
                openai_api_rs::v1::chat_completion::MessageRole::user => Role::User,
                openai_api_rs::v1::chat_completion::MessageRole::system => Role::System,
                openai_api_rs::v1::chat_completion::MessageRole::tool => Role::Tool,
                openai_api_rs::v1::chat_completion::MessageRole::assistant => Role::Assistant,
                _ => Role::Assistant,
            },
            message: message.content.clone(),
            audio: None,
            images: None,
            thinking: message.reasoning_content.clone(),
            function_calls,
            function_results: vec![],
        })
    }

    #[cfg(feature = "openai")]
    pub fn from_openai_chat_completion_stream_response(
        message: ChatCompletionStreamResponse,
    ) -> crate::Result<Message> {
        match message {
            ChatCompletionStreamResponse::ToolCall(toolcalls) => Ok(Message {
                role: Role::Assistant,
                message: None,
                audio: None,
                images: None,
                thinking: None,
                function_calls: toolcalls
                    .iter()
                    .map(|tc| FunctionCall::from_openai(tc.clone()))
                    .collect(),
                function_results: vec![],
            }),
            ChatCompletionStreamResponse::Content(content) => Ok(Message {
                role: Role::Assistant,
                message: Some(content),
                audio: None,
                images: None,
                thinking: None,
                function_calls: vec![],
                function_results: vec![],
            }),
            ChatCompletionStreamResponse::Done => Ok(Message {
                role: Role::Assistant,
                message: None,
                audio: None,
                images: None,
                thinking: None,
                function_calls: vec![],
                function_results: vec![],
            }),
        }
    }
}
