use serde::{Deserialize, Serialize};

/// Role of the message author
///
/// Possible values:
/// - System: Instructions or context for the LLM
/// - Tool: Messages generated by tools/functions
/// - Assistant: Responses from the LLM
/// - User: Input from the end-user
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Eq, Hash, PartialOrd, Ord)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    Tool,
    Assistant,
    User,
}

impl Role {
    #[cfg(feature = "openai")]
    pub fn to_openai(&self) -> openai_api_rs::v1::chat_completion::MessageRole {
        match self {
            Role::User => openai_api_rs::v1::chat_completion::MessageRole::user,
            Role::System => openai_api_rs::v1::chat_completion::MessageRole::system,
            Role::Tool => openai_api_rs::v1::chat_completion::MessageRole::tool,
            Role::Assistant => openai_api_rs::v1::chat_completion::MessageRole::assistant,
        }
    }

    #[cfg(feature = "openai")]
    pub fn from_openai(role: &openai_api_rs::v1::chat_completion::MessageRole) -> Self {
        match role {
            openai_api_rs::v1::chat_completion::MessageRole::user => Role::User,
            openai_api_rs::v1::chat_completion::MessageRole::system => Role::System,
            openai_api_rs::v1::chat_completion::MessageRole::tool => Role::Tool,
            openai_api_rs::v1::chat_completion::MessageRole::assistant => Role::Assistant,
            _ => Role::Assistant,
        }
    }

    #[cfg(feature = "google")]
    pub fn to_gemini(&self) -> gemini_rust::Role {
        match self {
            Role::User => gemini_rust::Role::User,
            _ => gemini_rust::Role::Model,
        }
    }

    #[cfg(feature = "google")]
    pub fn from_google(role: &gemini_rust::Role) -> Self {
        match role {
            gemini_rust::Role::User => Role::User,
            _ => Role::Assistant,
        }
    }

    #[cfg(feature = "ollama")]
    pub fn to_ollama(&self) -> ollama_rs::generation::chat::MessageRole {
        match self {
            Role::User => ollama_rs::generation::chat::MessageRole::User,
            Role::System => ollama_rs::generation::chat::MessageRole::System,
            Role::Tool => ollama_rs::generation::chat::MessageRole::Tool,
            Role::Assistant => ollama_rs::generation::chat::MessageRole::Assistant,
        }
    }

    #[cfg(feature = "ollama")]
    pub fn from_ollama(role: &ollama_rs::generation::chat::MessageRole) -> Self {
        match role {
            ollama_rs::generation::chat::MessageRole::User => Role::User,
            ollama_rs::generation::chat::MessageRole::System => Role::System,
            ollama_rs::generation::chat::MessageRole::Tool => Role::Tool,
            ollama_rs::generation::chat::MessageRole::Assistant => Role::Assistant,
        }
    }
}
