use serde::{Deserialize, Serialize};

/// Role of the message author
///
/// Possible values:
/// - System: Instructions or context for the LLM
/// - Tool: Messages generated by tools/functions
/// - Assistant: Responses from the LLM
/// - User: Input from the end-user
#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize, Eq, Hash, PartialOrd, Ord)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    Tool,
    #[default]
    Assistant,
    User,
}

impl Role {
    #[cfg(feature = "openai")]
    pub fn to_openai(&self) -> openai_api_rs::v1::chat_completion::MessageRole {
        match self {
            Role::User => openai_api_rs::v1::chat_completion::MessageRole::user,
            Role::System => openai_api_rs::v1::chat_completion::MessageRole::system,
            Role::Tool => openai_api_rs::v1::chat_completion::MessageRole::tool,
            Role::Assistant => openai_api_rs::v1::chat_completion::MessageRole::assistant,
        }
    }

    #[cfg(feature = "openai")]
    pub fn from_openai(role: &openai_api_rs::v1::chat_completion::MessageRole) -> Self {
        match role {
            openai_api_rs::v1::chat_completion::MessageRole::user => Role::User,
            openai_api_rs::v1::chat_completion::MessageRole::system => Role::System,
            openai_api_rs::v1::chat_completion::MessageRole::tool => Role::Tool,
            openai_api_rs::v1::chat_completion::MessageRole::assistant => Role::Assistant,
            _ => Role::Assistant,
        }
    }

    #[cfg(feature = "google")]
    pub fn to_gemini(&self) -> gemini_rust::Role {
        match self {
            Role::User => gemini_rust::Role::User,
            _ => gemini_rust::Role::Model,
        }
    }

    #[cfg(feature = "google")]
    pub fn from_google(role: &gemini_rust::Role) -> Self {
        match role {
            gemini_rust::Role::User => Role::User,
            _ => Role::Assistant,
        }
    }

    #[cfg(feature = "ollama")]
    pub fn to_ollama(&self) -> ollama_rs::generation::chat::MessageRole {
        match self {
            Role::User => ollama_rs::generation::chat::MessageRole::User,
            Role::System => ollama_rs::generation::chat::MessageRole::System,
            Role::Tool => ollama_rs::generation::chat::MessageRole::Tool,
            Role::Assistant => ollama_rs::generation::chat::MessageRole::Assistant,
        }
    }

    #[cfg(feature = "ollama")]
    pub fn from_ollama(role: &ollama_rs::generation::chat::MessageRole) -> Self {
        match role {
            ollama_rs::generation::chat::MessageRole::User => Role::User,
            ollama_rs::generation::chat::MessageRole::System => Role::System,
            ollama_rs::generation::chat::MessageRole::Tool => Role::Tool,
            ollama_rs::generation::chat::MessageRole::Assistant => Role::Assistant,
        }
    }

    #[cfg(feature = "openrouter")]
    pub fn to_openrouter(&self) -> openrouter_rs::types::Role {
        match self {
            Role::User => openrouter_rs::types::Role::User,
            Role::System => openrouter_rs::types::Role::System,
            Role::Tool => openrouter_rs::types::Role::Tool,
            Role::Assistant => openrouter_rs::types::Role::Assistant,
        }
    }

    #[cfg(feature = "openrouter")]
    pub fn from_openrouter(role: &openrouter_rs::types::Role) -> Self {
        match role {
            openrouter_rs::types::Role::User => Role::User,
            openrouter_rs::types::Role::System => Role::System,
            openrouter_rs::types::Role::Tool => Role::Tool,
            openrouter_rs::types::Role::Assistant => Role::Assistant,
            openrouter_rs::types::Role::Developer => Role::User,
        }
    }

    #[cfg(feature = "openrouter")]
    pub fn from_openrouter_str(role: &str) -> Self {
        match role {
            "user" => Role::User,
            "system" => Role::System,
            "tool" => Role::Tool,
            "assistant" => Role::Assistant,
            "developer" => Role::User,
            _ => Role::Assistant,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_role_serialization() {
        let roles = vec![
            (Role::System, "\"system\""),
            (Role::Tool, "\"tool\""),
            (Role::Assistant, "\"assistant\""),
            (Role::User, "\"user\""),
        ];

        for (role, expected) in roles {
            assert_eq!(serde_json::to_string(&role).unwrap(), expected);
            let deserialized: Role = serde_json::from_str(expected).unwrap();
            assert_eq!(deserialized, role);
        }
    }

    #[test]
    fn test_role_ordering_and_hash() {
        use std::collections::HashSet;

        let mut set = HashSet::new();
        set.insert(Role::User);
        set.insert(Role::User);

        assert_eq!(set.len(), 1);
        assert!(Role::System < Role::User);
    }

    #[cfg(feature = "openai")]
    #[test]
    fn test_openai_role_mapping() {
        use openai_api_rs::v1::chat_completion::MessageRole as ORole;

        let pairs = vec![
            (Role::User, ORole::user),
            (Role::System, ORole::system),
            (Role::Tool, ORole::tool),
            (Role::Assistant, ORole::assistant),
        ];

        for (internal, openai) in pairs {
            assert!(matches!(internal.to_openai(), r if r == openai));
            assert_eq!(Role::from_openai(&openai), internal);
        }

        // Test fallback for unexpected OpenAI roles (if any)
        // Since OpenAI SDK uses an enum, we test the default mapping
        assert_eq!(Role::from_openai(&ORole::assistant), Role::Assistant);
    }

    #[cfg(feature = "google")]
    #[test]
    fn test_google_role_mapping() {
        use gemini_rust::Role as GRole;

        // User maps to User
        assert!(matches!(Role::User.to_gemini(), GRole::User));
        assert_eq!(Role::from_google(&GRole::User), Role::User);

        // System/Tool/Assistant map to Model in Gemini's two-role system
        assert!(matches!(Role::System.to_gemini(), GRole::Model));
        assert!(matches!(Role::Assistant.to_gemini(), GRole::Model));
        assert!(matches!(Role::Tool.to_gemini(), GRole::Model));

        assert_eq!(Role::from_google(&GRole::Model), Role::Assistant);
    }

    #[cfg(feature = "ollama")]
    #[test]
    fn test_ollama_role_mapping() {
        use ollama_rs::generation::chat::MessageRole as OlRole;

        let pairs = vec![
            (Role::User, OlRole::User),
            (Role::System, OlRole::System),
            (Role::Tool, OlRole::Tool),
            (Role::Assistant, OlRole::Assistant),
        ];

        for (internal, ollama) in pairs {
            assert!(matches!(internal.to_ollama(), r if r == ollama));
            assert_eq!(Role::from_ollama(&ollama), internal);
        }
    }
}
