use serde::{Deserialize, Serialize};

/// Role of the message author
///
/// Possible values:
/// - System: Instructions or context for the LLM
/// - Tool: Messages generated by tools/functions
/// - Assistant: Responses from the LLM
/// - User: Input from the end-user
#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize, Eq, Hash, PartialOrd, Ord)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    Tool,
    #[default]
    Assistant,
    User,
    Developer,
}
